// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/project_api_key.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectAPIKeyService_GetApiDataByKey_FullMethodName = "/project.ProjectAPIKeyService/GetApiDataByKey"
)

// ProjectAPIKeyServiceClient is the client API for ProjectAPIKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectAPIKeyServiceClient interface {
	GetApiDataByKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type projectAPIKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectAPIKeyServiceClient(cc grpc.ClientConnInterface) ProjectAPIKeyServiceClient {
	return &projectAPIKeyServiceClient{cc}
}

func (c *projectAPIKeyServiceClient) GetApiDataByKey(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ProjectAPIKeyService_GetApiDataByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectAPIKeyServiceServer is the server API for ProjectAPIKeyService service.
// All implementations must embed UnimplementedProjectAPIKeyServiceServer
// for forward compatibility.
type ProjectAPIKeyServiceServer interface {
	GetApiDataByKey(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedProjectAPIKeyServiceServer()
}

// UnimplementedProjectAPIKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectAPIKeyServiceServer struct{}

func (UnimplementedProjectAPIKeyServiceServer) GetApiDataByKey(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiDataByKey not implemented")
}
func (UnimplementedProjectAPIKeyServiceServer) mustEmbedUnimplementedProjectAPIKeyServiceServer() {}
func (UnimplementedProjectAPIKeyServiceServer) testEmbeddedByValue()                              {}

// UnsafeProjectAPIKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectAPIKeyServiceServer will
// result in compilation errors.
type UnsafeProjectAPIKeyServiceServer interface {
	mustEmbedUnimplementedProjectAPIKeyServiceServer()
}

func RegisterProjectAPIKeyServiceServer(s grpc.ServiceRegistrar, srv ProjectAPIKeyServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectAPIKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectAPIKeyService_ServiceDesc, srv)
}

func _ProjectAPIKeyService_GetApiDataByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectAPIKeyServiceServer).GetApiDataByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectAPIKeyService_GetApiDataByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectAPIKeyServiceServer).GetApiDataByKey(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectAPIKeyService_ServiceDesc is the grpc.ServiceDesc for ProjectAPIKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectAPIKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectAPIKeyService",
	HandlerType: (*ProjectAPIKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiDataByKey",
			Handler:    _ProjectAPIKeyService_GetApiDataByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/project_api_key.proto",
}
