// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/project_api_key.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_project_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_project_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TanentId      string                 `protobuf:"bytes,3,opt,name=tanent_id,json=tanentId,proto3" json:"tanent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_project_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_project_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Response) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Response) GetTanentId() string {
	if x != nil {
		return x.TanentId
	}
	return ""
}

var File_proto_project_api_key_proto protoreflect.FileDescriptor

const file_proto_project_api_key_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/project_api_key.proto\x12\aproject\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"_\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttanent_id\x18\x03 \x01(\tR\btanentId2N\n" +
	"\x14ProjectAPIKeyService\x126\n" +
	"\x0fGetApiDataByKey\x12\x10.project.Request\x1a\x11.project.ResponseBUZSgithub.com/indalyadav56/logify/services/project-service/internal/transport/grpc/protob\x06proto3"

var (
	file_proto_project_api_key_proto_rawDescOnce sync.Once
	file_proto_project_api_key_proto_rawDescData []byte
)

func file_proto_project_api_key_proto_rawDescGZIP() []byte {
	file_proto_project_api_key_proto_rawDescOnce.Do(func() {
		file_proto_project_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_api_key_proto_rawDesc), len(file_proto_project_api_key_proto_rawDesc)))
	})
	return file_proto_project_api_key_proto_rawDescData
}

var file_proto_project_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_project_api_key_proto_goTypes = []any{
	(*Request)(nil),  // 0: project.Request
	(*Response)(nil), // 1: project.Response
}
var file_proto_project_api_key_proto_depIdxs = []int32{
	0, // 0: project.ProjectAPIKeyService.GetApiDataByKey:input_type -> project.Request
	1, // 1: project.ProjectAPIKeyService.GetApiDataByKey:output_type -> project.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_project_api_key_proto_init() }
func file_proto_project_api_key_proto_init() {
	if File_proto_project_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_api_key_proto_rawDesc), len(file_proto_project_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_api_key_proto_goTypes,
		DependencyIndexes: file_proto_project_api_key_proto_depIdxs,
		MessageInfos:      file_proto_project_api_key_proto_msgTypes,
	}.Build()
	File_proto_project_api_key_proto = out.File
	file_proto_project_api_key_proto_goTypes = nil
	file_proto_project_api_key_proto_depIdxs = nil
}
